# yaml-language-server: $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
---
name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - v*
